# The entries defined in this section will be passed to the session as environment variables when it is started
[env]
#ENV_VARIABLE = "value"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Classic"
font_name = "Cantarell 16"
icon_theme_name = "Papirus-Dark"
#theme_name = ""

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
