# Colors (Alabaster Dark)

# Default colors
[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

# Cursor colors
[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

# Normal colors
[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

# Bright colors
[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'
